### ISSUE TITLE
Revamp script bug

### ISSUE THREAD

**Issue by zhouyuan1119** [cornell-zhang/datuner#26]
I am trying to run the test `flows/vivado_hls_spam` on the `revamp` branch. When running the command
```
python $DATUNER_HOME/src/host.py -f custom -b 20 -t 1d:0h:0m:0s -p 1
```
DATuner breaks inside `host.py` with the following messages:
```
[     0s]    INFO the current work space is: /work/zhang-x1/users/yz882/cornell-zhang/datuner-revamp/datuner/flows/custom
[     0s]    INFO time limit: 86400 seconds
rm: cannot remove ‘package.zip’: No such file or directory
cp: omitting directory ‘/work/zhang-x1/users/yz882/cornell-zhang/datuner-revamp/datuner//flows/custom/data’
cp: omitting directory ‘/work/zhang-x1/users/yz882/cornell-zhang/datuner-revamp/datuner//flows/custom/files’
Traceback (most recent call last):
  File "/work/zhang-x1/users/yz882/cornell-zhang/datuner-revamp/datuner//src/host.py", line 308, in <module>
    os.system('cp -R ' + designdir + '/* files/design')
NameError: name 'designdir' is not defined
```
If we go into the file `host.py` we can see the variable `designdir` is never defined.

**Comment by Hecmay** [comment]
The name "designdir" is supposed to be assigned by the user in the custom.py. And I think that you should put the spam-filter scripts and data into the "designdir" instead of the `datuner/flows/custom/` directory.

**Comment by Hecmay** [comment]
@tincanman @eu49  I also have some questions about the latest commitment of the revamp branch:
1. What is difference between "SweepParameter" and "EnumParameter" in the parameter configuration scripts?
2.  What is point of using sweep_function instead of tune_function while seep count >1

**Comment by zhangzhiru** [comment]
Re. the designdir issue, we need to prompt proper error messages instead of letting the tool generate internal error.

**Comment by Hecmay** [comment]
Yes, the required parameter should be checked before usage. I will try to clean up the scripts after discussing with Ecenur and Tian.

**Comment by eu49** [comment]
@Hecmay SweepParameter defines the sweeping space for the corresponding variable. The aim is to evaluate the design on each sweep value (while the EnumParameters are fixed). This mode is useful when for example you want to see the effect of increasing the bitwidth on the resource utilization. In this case, you can sweep through different bitwidth values and observe the DSP usage.

**Comment by zhouyuan1119** [comment]
Just tried again. The example still got stuck after launching the workers. We have to make some additional changes to the scripts so that it can reach that step without any errors. Here is a list what Ecenur and I did:

1. Copy the `vivado_hls_spam` example to a working directory;
2. Rename `config.py` to `custom.py`;
3. Inside `custom.py`, remove the `budget` and `flow` rows, change `workspace`, `machines`, and `server_address` to the correct values, and add two lines `design_dir = "/work/zhang-x1/users/yz882/fixed_point_tuning/vivado_hls_spam"`, `top_module = "some_module"` so that the host script would not break;
4. In `host.py`, comment out the imports under line 49 and replace with `from custom import *`;
5. In `host.py`, add `source ~/.bashrc` to the command string in line 321 so that the tool paths can be correctly set for the clients;
6. Finally, in my `bashrc`, put the DATuner setup commands to the very top so that they always get executed. It seems some other commands in my `bashrc` can easily get stuck. 

After all these, the example gets stuck with the following outputs:
```
[     0s]    INFO the current work space is: /work/zhang-x1/users/yz882/fixed_point_tuning/vivado_hls_spam
[     0s]    INFO time limit: 86400 seconds
cp: cannot stat ‘/work/zhang-x1/users/yz882/cornell-zhang/datuner-revamp/datuner/flows/custom/*’: No such file or directory
cp: cannot copy a directory, ‘/work/zhang-x1/users/yz882/fixed_point_tuning/vivado_hls_spam/files’, into itself, ‘files/design/files’
  adding: custom.py (deflated 74%)
  adding: design/ (stored 0%)
  adding: design/csim.tcl (deflated 53%)
  adding: design/custom.py (deflated 74%)
  adding: design/custom.pyc (deflated 65%)
  adding: design/data/ (stored 0%)
  adding: design/data/newfeats.dat (deflated 95%)
  adding: design/data/newlabels.dat (deflated 94%)
  adding: design/data/shuffledfeats.dat (deflated 94%)
  adding: design/data/shuffledlabels.dat (deflated 90%)
  adding: design/_dispy_20180410113441 (deflated 97%)
  adding: design/files/ (stored 0%)
  adding: design/files/tune.py (deflated 60%)
  adding: design/files/custom.py (deflated 74%)
  adding: design/files/design/ (stored 0%)
  adding: design/files/design/csim.tcl (deflated 53%)
  adding: design/files/design/custom.py (deflated 74%)
  adding: design/files/design/custom.pyc (deflated 65%)
  adding: design/LogisticRegression_accel.cpp (deflated 71%)
  adding: design/LogisticRegression_accel.h (deflated 71%)
  adding: design/LogisticRegression.cpp (deflated 77%)
  adding: design/lut.h (deflated 84%)
  adding: design/Makefile (deflated 47%)
  adding: design/README.md (deflated 58%)
  adding: design/results.db (deflated 91%)
  adding: design/setup.py (deflated 63%)
  adding: design/timer.h (deflated 73%)
  adding: tune.py (deflated 60%)
2018-04-10 11:53:59 pycos - version 4.6.5 with epoll I/O notifier
2018-04-10 11:53:59 dispy - dispy client version: 4.8.5
2018-04-10 11:53:59 dispy - Storing fault recovery information in "_dispy_20180410115359"
dispynode.py                                                                                           100%   85KB  36.5MB/s   00:00    

  "psutil" module is not available;
    node status (CPU, memory, disk and swap space usage) will not be sent to clients

2018-04-10 11:54:00 dispynode - dispynode version: 4.8.5, PID: 82990
2018-04-10 11:54:00 pycos - version 4.6.5 with epoll I/O notifier
```
Since there's no log file from dispy we don't know what it is doing.

**Comment by Hecmay** [comment]
The dispy client (master) is waiting for the response from the slaves, so there is no log printed out. Since there is no dispynode slave that was triggered in the scripts of "auto-tuning" mode, as a temporary solution, we may run the slave (on the same machine) manually,  and then the tuning process can be triggered successfully.

Another thing is that: the `setup.py` was copied into the wrong location so that the `tune.py` failed to reach it. Followed is the error thrown by the dispynode slave:
```
Traceback (most recent call last):     
  File "tune.py", line 12, in <module>
    from setup import *                                  
ImportError: No module named setup   
```
add `os.system('cp ' + designdir + '/setup.py files/')` in `host.py` +310 and it can work.

The scripts of working flow is still kind of messy, and I will try to clean it up theses days.

**Comment by eu49** [comment]
Shaojie, please refer to [this commit](https://github.com/cornell-zhang/datuner/commit/c00f8b634dda6992ec28f3b64181100cbf4fe836) and [issue ](https://github.com/cornell-zhang/datuner/issues/22) for the first problem you mentioned. It should be working.

For the second part, it actually was not only due to copying _setup.py_ to the wrong directory, please see [my latest commit](https://github.com/cornell-zhang/datuner/commit/57cfa34d355b4b656c9dadff6f19399715a07b1d). Host needs to copy _adddeps_ and _programWrapper_ modules to where the tuning script exists (i.e. the _files_ folder under the workdir). Secondly, as the custom files are not necessarily under $DATUNER_HOME/flows/custom (they can be anywhere of user's choice), the files are copied to the _design_ folder under _files_ without being copied to _files_. So, I added an if statement for copying designdir of custom files to the _files_ folder under the workdir.
